language: rust
install:
    - curl -O http://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
    - tar xfz rust-nightly-x86_64-unknown-linux-gnu.tar.gz
    - (cd rust-nightly-x86_64-unknown-linux-gnu/ && sudo ./install.sh)
# Voodoo to get glfw on the system
before_script:
    - sudo apt-get install libXxf86vm-dev
    - git clone https://github.com/glfw/glfw.git
    - cd glfw
    - git checkout 3.0.3
    - cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=/usr
    - make
    - sudo make install
    - cd ..
script:
    - rustc --version
    - make
    - make check
branches:
    only:
        - rust
