language: rust
sudo: required
services:
  - docker
rust:
  - 1.1.0
  - beta
  - nightly
script:
  - cargo test
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      docker pull alexcrichton/rust-centos-dist;
      docker run -v $HOME/rust:/rust:ro -v `pwd`:/home/rustbuild
        -it alexcrichton/rust-centos-dist /bin/sh -c
          'PATH=$PATH:/rust/bin LD_LIBRARY_PATH=/rust/lib cargo build --release';
    else
      cargo build --release;
    fi
branches:
  only:
    - rust
os:
  - linux
  - osx
env:
  global:
    - MACOSX_DEPLOYMENT_TARGET=10.7
notifications:
  email:
    on_success: never
deploy:
  provider: releases
  api_key:
    secure: SC4XXEF25nu0teN4dyGtQ8WAiIGEoWxm39Bty3S50ZoDlavcmS3Db6KDJE6SFTK25O7rqld1fbAW/eS0znvl6lFjXrCuDFE++yicX1OKB8kxYMzrrLK7jlCemRPokyfbaGOAv4LHkPudwWp1Ed2SKSLUuUDbJCWjoI/R1P/yVCo=
  file: target/releases/jba
  on:
    tags: true
    repo: alexcrichton/jba
    branch: rust
    rust: nightly
