language: rust
sudo: false
rust:
  - 1.0.0
  - beta
  - nightly
script:
    - cargo build --verbose
    - cargo test --verbose
branches:
  only:
    - rust

notifications:
  email:
    on_success: never
