[project]

name = "jba"
version = "0.1.0"
authors = []

[dependencies]
time = "0.1"
log = "0.2"
env_logger = "0.2"
getopts = "0.2"
libc = "0.1"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs"
